#!/usr/bin/env bash
# gen/android is fully regenerated by `cargo tauri android init` and is
# git-ignored (CLAUDE.md's own note) — this patch doesn't survive a fresh
# `rm -rf gen/android && cargo tauri android init`, so run this script
# again after any such regeneration. It's idempotent: safe to run
# multiple times against the same manifest.
#
# Adds the CAMERA permission the QR-scan feature (dist/main.js's
# getUserMedia call) needs — confirmed live against wry's own Android
# WebChromeClient source that it already prompts for this permission at
# runtime once it's declared here; this script is the one-time manifest
# declaration that request needs to succeed.
set -euo pipefail
cd "$(dirname "$0")/.."
MANIFEST="src-tauri/gen/android/app/src/main/AndroidManifest.xml"
if [ ! -f "$MANIFEST" ]; then
  echo "error: $MANIFEST not found — run 'cargo tauri android init' first" >&2
  exit 1
fi
if grep -q 'android.permission.CAMERA' "$MANIFEST"; then
  echo "CAMERA permission already present in $MANIFEST — nothing to do"
  exit 0
fi
sed -i 's#<uses-permission android:name="android.permission.INTERNET" />#<uses-permission android:name="android.permission.INTERNET" />\n    <uses-permission android:name="android.permission.CAMERA" />\n    <uses-feature android:name="android.hardware.camera" android:required="false" />#' "$MANIFEST"
echo "patched $MANIFEST"
